### PR TITLE
TMCRootManager: implemented RNTuple writer

### PR DESCRIPTION
**Pull request by karabowi**
Allows the TMCRootManager store data in TTree or RNTuple format.

### CODE REVIEW

File: source/include/TMCRootManager.h [hunk 1]
```diff
@@ -18,9 +18,22 @@
 #include "TMCtls.h"
 #include <Rtypes.h>
 
+#include "TFile.h"
+#include "TTree.h"
```
Comment (ihrivnac) [inline source/include/TMCRootManager.h:22]: These includes should be removed from `.cxx`

File: source/include/TMCRootManager.h [hunk 2]
```diff
@@ -77,9 +99,18 @@ class TMCRootManager {
 
    // data members
    Int_t fId;        // This manager ID
-   TFile *fFile;     // Root output file
-   TTree *fTree;     // Root output tree
-   Bool_t fIsClosed; // Info whether its file was closed
+   TFile *fFile {0};     // Root output file
+   TTree *fTree {0};     // Root output tree
```
Comment (ihrivnac) [inline source/include/TMCRootManager.h]: We can use `nullptr`

File: source/src/TMCRootManager.cxx [hunk 3]
```diff
@@ -141,7 +147,11 @@ TMCRootManager::~TMCRootManager()
 //_____________________________________________________________________________
 void TMCRootManager::OpenFile(const char *projectName, FileMode fileMode, Int_t threadRank)
 {
-   TString fileName(projectName);
+   TString fileName = Form("T%s",projectName);
+   if (fStorageMode == kRNTuple) {
+      fileName = Form("R%s",projectName);
+   }
```
Comment (ihrivnac) [inline source/src/TMCRootManager.cxx]: The file name should not be modified here; this should be removed.

Then in E03 example, we should better duplicate `run_g4.C` in `run_g4a,b,c,d.C` to avoid overwrite the output from each example.

**Comment by karabowi** [comment]
I have applied the requested changes.
Thank you for pointing them out.

File: source/include/TMCRootManager.h [hunk 4]
```diff
@@ -18,9 +18,26 @@
...
-class TTree;
+
+using ROOT::Experimental::RNTupleParallelWriter;
+
+using ROOT::RNTupleFillStatus;
+using REntry = ROOT::REntry;
+using RNTupleModel = ROOT::RNTupleModel;
+using RNTupleWriter = ROOT::RNTupleWriter;
+using RNTupleFillContext = ROOT::Experimental::RNTupleFillContext;
+using RNTParaWriter = ROOT::Experimental::RNTupleParallelWriter;
```
Comment (ihrivnac) [inline source/include/TMCRootManager.h]: The `Experimental::` was removed since ROOT v6.38.00; when I compiled with ROOT v6.40.02, this was causing compilation error.
As we should not require ROOT build with experimental features (ROOT 7) for building `vmc`, I suggest to remove `Experimental::` and add a test for ROOT version 
```c++
#if (ROOT_VERSION_CODE >= ROOT_VERSION(6, 38, 0)))
using RNTupleFillContext = ROOT::Experimental::RNTupleFillContext;
using RNTParaWriter = ROOT::Experimental::RNTupleParallelWriter;
#endif
```
and also around the code requiring these classes below.

Comment (ihrivnac) [reply source/include/TMCRootManager.h]: Thank you for this update.  I can now compile vmc with ROOT versions v6.36.14 and  v6.40.02; but the E03d  example in https://github.com/vmc-project/geant4_vmc/pull/85 does not compile with v6.36.14.
So I prefer to wait with merging when both PRs will work together.
